### ISSUE TITLE
4.3 patch 46

### ISSUE THREAD

**Issue by LukasBacigal** [calid/bash#2]
I really like your mod, but newest version of BASH at Ubuntu 16.04 is 4.3.46(1) so I guess there are some new patches, would you rebase/merge this mod onto that version?

**Comment by calid** [comment]
Rebased onto latest 4.3.46 master.  Since I rebased the branch you'll need to fetch and reset hard your local branch to the origin version.  Let me know if you have any issues.  Cheers!
