### ISSUE TITLE
configure step failing on missing readline

### ISSUE THREAD

**Issue by ddickstein** [calid/bash#3]
I'm running CentOS Linux 7.2 and am getting the following error when I run `./configure`

```
checking...
configure: creating ./config.status
config.status: creating Makefile
config.status: creating builtins/Makefile
config.status: error: cannot find input file: `lib/readline/Makefile.in'
```

If I ignore this error and try running `make`, it fails with:

```
make: *** No rule to make target `lib/readline/history.h', needed by `shell.o'.  Stop.
```

Yum reports that Readline 6.2 is currently installed.

**Comment by calid** [comment]
Did you clone the readline submodule?  `git submodule update --init`

**Comment by ddickstein** [comment]
No, I did not, because I'm apparently terrible at following directions.

**Comment by ddickstein** [comment]
brilliant work, thank you!
